curl 'http://10.0.1.111/luci/admin/lm/set?sp=85' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: */*' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.30 Safari/537.36' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'Referer: http://10.0.1.111/luci/admin/lm/home' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cookie: sysauth=xxxx' \
  --compressed \
  --insecure